openapi: 3.0.3
info:
  title: Supplier–Consumer MVP API
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /healthz:
    get:
      summary: Health check
      responses:
        "200":
          description: ok
  /links:
    post:
      summary: Request a link (consumer->supplier)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [supplier_id]
              properties:
                supplier_id: { type: string, format: uuid }
      responses:
        "201": { description: created }
  /links/{id}/accept:
    post:
      summary: Accept link (supplier owner/admin)
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string, format: uuid }
      responses:
        "200": { description: accepted }
